services:
  splitter:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.splitter.rule=Host(`splitter.homelab`)'
      - 'traefik.http.services.splitter.loadbalancer.server.port=3000'
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
